### ISSUE TITLE
Getting a "warning" related to overwrite parameter

### ISSUE THREAD

**Issue by pauldps** [allenevans/set-env#7]
```
##[warning]Unexpected input 'YT_API_KEY', valid inputs are ['overwrite']
Run allenevans/set-env@v1.1.0
  with:
    YT_API_KEY: ***
    overwrite: true
  env:
    PATH: /home/runner/.rubies/ruby-
```

`YT_API_KEY` is an env variable I'm trying to set. The relevant part of my workflow file:

```yaml
    - name: Set environment variables
      uses: allenevans/set-env@v1.1.0
      with:
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
```

If I add `overwrite` to my workflow file, the warning persists:

```
##[warning]Unexpected input 'YT_API_KEY', valid inputs are ['overwrite']
Run allenevans/set-env@v1.1.0
  with:
    overwrite: true
    YT_API_KEY: ***
  env:
    PATH: /home/runner/.rubies/ruby-
```

Functionality doesn't seem to be affected, as the env var seems to be correctly set for the next steps.
